### PR TITLE
Corrected hour24Padded using valid 0-23 instead of 1-24

### PR DESCRIPTION
**Pull request by ivanceras**
Fix for issue https://github.com/abadi199/dateparser/issues/11
The formatting is also changed from elm-format

---
This change is [Reviewable](https://reviewable.io/reviews/abadi199/dateparser/12)

### CODE REVIEW

**Comment by abadi199** [comment]
Thanks for the PR @ivanceras. Everything looks good. 
The formatting differences are because I'm using the experimental version of elm-format (https://github.com/avh4/elm-format#experimental-version) which remove the indentation for the `in` block. If you don't mind reformatting the code with the `elm-format@exp`, that will be great. If not, it's not a big deal, I will still merge this PR 😃

**Comment by ivanceras** [comment]
@abadi199 I will try to use the experimental version of elm-format

**Comment by ivanceras** [comment]
@abadi199 this is now formatted using elm-format@exp version.

**Comment by abadi199** [comment]
Awesome. Thanks for your contribution.

**Pull request merged**
